baseURL = "https://userstyles.world/"
languageCode = "en-us"
title = "UserStyles.world"
enableGitInfo = true

[outputs]
    home = [ "HTML", "RSS", "JSON" ]

[params]
    titleSeparator = " — "
    source = "https://github.com/vednoc/userstyles.world"
    debug = false

[author]
    name = "vednoc"
    link = "https://www.github.com/vednoc"
