baseURL = "https://userstyles.world/"
languageCode = "en-us"
title = "UserStyles.World"

[params]
    titleSeparator = "—"
    debug = false

[author]
  name = "vednoc"
  link = "https://www.github.com/vednoc"
