name: Redeploy

on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Ping Vercel's redeploy hook
              run: curl -X GET ${{ secrets.vercel_redeploy }}
